# Consul as a service discovery tier
consul:
    image: progrium/consul:latest
    command: >
      -server
      -bootstrap-expect 1
      -ui-dir /ui
    restart: always
    mem_limit: 128m
    ports:
        - 53
        - 8300
        - 8301
        - 8302
        - 8400
        - 8500
    dns:
       - 127.0.0.1
    labels:
        - triton.cns.services=tb-consul

# Manually bootstrap the first instance, then...
# Scale this tier and each additional container/instance will automatically
# self-configure as a member of the cluster
couchbase:
    image: autopilotpattern/couchbase:enterprise-4.0.0-r1
    restart: always
    links:
        - consul
    mem_limit: 1g
    ports:
        - 8091
        - 8092
        - 8093
        - 11207
        - 11210
        - 11211
        - 18091
        - 18092
    env_file: _env
    environment:
        - CONSUL_HOST=http://consul:8500
        - COUCHBASE_SERVICE_NAME=couchbase
    labels:
        - triton.cns.services=tb-couchbase

# the main application
touchbase:
    build: .
    links:
    - consul
    mem_limit: 128m
    ports:
    - 3000
    restart: always
    command: >
      /opt/containerbuddy/containerbuddy
      -config file:///opt/containerbuddy/touchbase.json
      /usr/local/bin/run-touchbase.sh
    labels:
        - triton.cns.services=tb-touchbase

# Nginx as a load-balancing tier and reverse proxy
nginx:
    build: nginx/
    mem_limit: 512m
    ports:
    - 80
    expose:
    - 80
    links:
    - consul:consul
    restart: always
    command: >
      /opt/containerbuddy/containerbuddy
      -config file:///opt/containerbuddy/nginx.json
      nginx -g "daemon off;"
    labels:
        - triton.cns.services=tb-nginx
